---
name: Synchronise Upstream

on:
  # Run at 21:30 on Sundays
  schedule:
    - cron: "31 21 * * 1"
  # Manual trigger
  workflow_dispatch:

permissions:
  contents: write
  packages: read
  issues: write
  pull-requests: write

jobs:
  template-sync:
    name: Template Synchronise
    runs-on: ubuntu-latest
    env:
      SYNCHRONISER_TOKEN: ${% raw %}{{ secrets.SYNCHRONISER_TOKEN || secrets.GITHUB_TOKEN }}{% endraw %}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          token: ${% raw %}{{ env.SYNCHRONISER_TOKEN }}{% endraw %}

      - name: Render and synchronise the template repository
        uses: n3tuk/action-synchronise-upstream@v1.0.0
        with:
          token: ${% raw %}{{ env.SYNCHRONISER_TOKEN }}{% endraw %}
          repository: n3tuk/template-terraform-module
          labels: type/dependencies,release/skip,priority/normal
