---
name: Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  issues: write
  checks: write
  pull-requests: write

jobs:
  terraform-integrations:
    # This job name must match the name of call called Workflow in order for
    # the name to successfully match any required status checks within the
    # branch protections
    name: Terraform Integrations
    uses: ./.github/workflows/terraform-integrations.yaml
    secrets: inherit
