---
version: 2

# For both Terraform modules and Terraform configurations, the checks performed
# by Dependabot are distributed across the week to give time for the checks to
# be made, reviewed, and merged, and then (if required) new releases made, which
# in turn will allow the following updates to take these releases into account.
#
# Friday:
#   - 12:00 GitHub Actions
#   - 16:00 Go modules in TerraTest
#   - 18:00 Sub-modules in Terraform modules (if present)
# Saturday:
#   - 18:00 Modules in Terraform module
# Sunday:
#   - 18:00 Examples in Terraform modules (if present)
#           Examples are delayed as some updates can be duplicate the updated
#           made through the module in Terraform module update above, so this
#           will reduce the chances of duplicated, and hence redundant, pull
#           requests being made by Dependabot.

updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "12:00"
      timezone: "Europe/London"
    reviewers:
      - n3tuk/admin
    commit-message:
      prefix: actions
      include: scope
    labels:
      - type/dependencies
      - update/github-workflows
      - release/chore
      - priority/normal

  - package-ecosystem: gomod
    directory: tests
    schedule:
      interval: weekly
      day: friday
      time: "16:00"
      timezone: "Europe/London"
    reviewers:
      - n3tuk/admin
    commit-message:
      prefix: go
      include: scope
    labels:
      - type/dependencies
      - update/terraform
      - release/chore
      - priority/normal
{%- for name in cookiecutter.components.submodules|sort %}

  - package-ecosystem: terraform
    directory: submodules/{{ name }}
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
      timezone: "Europe/London"
    registries:
      - terraform-cloud
    reviewers:
      - n3tuk/admin
    commit-message:
      prefix: terraform
      include: scope
    labels:
      - type/dependencies
      - update/terraform
      - release/chore
      - priority/normal
{%- endfor %}

  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: daily
      day: saturday
      time: "18:00"
      timezone: "Europe/London"
    registries:
      - terraform-cloud
    reviewers:
      - n3tuk/admin
    commit-message:
      prefix: terraform
      include: scope
    labels:
      - type/dependencies
      - update/terraform
      - release/chore
      - priority/normal
{%- for name in cookiecutter.components.examples|sort %}

  - package-ecosystem: terraform
    directory: examples/{{ name }}
    schedule:
      interval: weekly
      day: sunday
      time: "18:00"
      timezone: "Europe/London"
    registries:
      - terraform-cloud
    reviewers:
      - n3tuk/admin
    commit-message:
      prefix: terraform
      include: scope
    labels:
      - type/dependencies
      - update/terraform
      - release/chore
      - priority/normal
{%- endfor %}

registries:
  terraform-cloud:
    type: terraform-registry
    url: https://app.terraform.io
    token: ${% raw %}{{ secrets.TFE_TOKEN }}{% endraw %}
