---
formatter: markdown table
version: ">= 0.16.0, < 1.0.0"

sort:
  enabled: true
  by: required

settings:
  # Only use Terraform configuration for versions
  lockfile: false
  read-comments: false

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {% raw %}{{ .Content }}{% endraw %}
    <!-- END_TF_DOCS -->
